# Generated by Django 4.2.7 on 2023-11-07 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.TextField()),
                ('Legal_or_Natural_Person', models.CharField(choices=[('юридична', 'юридична'), ('фізична', 'фізична')], max_length=50)),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Contact_Person', models.TextField()),
                ('Bank_Account', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.TextField()),
                ('Price', models.FloatField()),
                ('Quantity_In_Store', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('Sale_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Sale_Date', models.DateField()),
                ('Sold_Quantity', models.IntegerField()),
                ('Discount', models.FloatField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('Payment_Method', models.CharField(choices=[('готівковий', 'готівковий'), ('безготівковий', 'безготівковий')], max_length=50)),
                ('Need_Delivery', models.BooleanField()),
                ('Delivery_Cost', models.FloatField()),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydjangoapp.customers')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydjangoapp.products')),
            ],
        ),
    ]
